### ISSUE TITLE
Kiro corrupted all files, charged me to fix them

### ISSUE THREAD

**Issue by fredzannarbor** [kirodotdev/Kiro#2185]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/kirodotdev/Kiro/issues?q=is%3Aissue+)

### Operating System

darwin

### Kiro Version

0.2.13

### Bug Description

ROOT CAUSE IDENTIFIED: The files contain literal \n and \" characters instead of actual newlines and quotes. This happened during the initial file creation process where the content was improperly escaped.

I'm still in the middle of untangling this.

### Steps to Reproduce

Just mind your own business, Kiro will screw it up on its own.

### Expected Behavior

Kiro should not have corrupted 60+ files, then charged me to fix them.

### Conversation ID

619a9fb3-1b48-4086-9e52-e47f3a3ae8e3
3f744b51-d02f-4cd1-ae02-f122e1873b9d
16108067-373d-4755-b743-5b07f44ee7c1
c421a603-4fa9-4af3-a80e-26134c41482c
0bb0a209-b123-4449-b67d-552fba3173d0

### Additional Context

The issue finally resolved and all UI pages loading correctly 2 hours and approximately 250 Vibe credits later.

**Comment by suruchi-aws** [comment]
Hi @fredzannarbor I see the issue was resolved for you. Regarding vibe credit usage, please go through this announcement for the changes we recently announced for Kiro:
https://discord.com/channels/1374034175430230016/1390198027016208414/1407544407808409663

**Comment by fredzannarbor** [comment]
Sorry to say the changes are still a bit confusing.

@atomicsphinx raises a good issue. What does "not charge for the month of
August" mean? I already paid $40. Will i get it back? And my billing page
still shows vibe use, spec use, and overages. Am I paying for any overages
in August?

[image: Screenshot 2025-08-20 at 20.59.09.png]
---
Fred Zimmerman, Publisher
Nimble Books LLC
The AI Lab for Book-Lovers <http://NimbleBooks.com>
