### ISSUE TITLE
Validation failed calling firecrawl... no schema with key or ref

### ISSUE THREAD

**Issue by huachuman** [kirodotdev/Kiro#3638]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/kirodotdev/Kiro/issues?q=is%3Aissue+)

### Operating System

Windows 11

### Kiro Version

0.5.0

### Bug Description

Validation failed calling firecrawl_scrape with args {"url":"https://example.com","formats":["markdown"]}: no schema with key or ref "https://json-schema.org/draft/2020-12/schema"

### Steps to Reproduce

Add firecrawl mcp to config:

```
"firecrawl-mcp": {
      "command": "npx",
      "args": [
        "-y",
        "firecrawl-mcp"
      ],
      "env": {
        "FIRECRAWL_API_KEY": "redacted"
      },
      "disabled": false
    },
```

Then make a request to firecrawl mcp.

### Expected Behavior

... it works...?

**Comment by AnilMaktala** [comment]
Hey @huachuman, Thanks for raising this. We just released remote MCP server support, and I successfully connected to the Firecarwl MCP server with the following config. Please try it and let me know if it fixes your problem.

```
    "firecrawl": {
      "url": "https://mcp.firecrawl.dev/v2/mcp",
      "headers": {
        "Authorization": "Bearer ${FIRECRAWL_API_KEY}}"
      },
      "env": {
        "FIRECRAWL_API_KEY": "<Add API KEY>"
      }
    }
```

<img width="447" height="252" alt="Image" src="https://github.com/user-attachments/assets/cecc9e9f-bf7d-4a6b-8800-bc4b0e23e36b" />

**Comment by huachuman** [comment]
Connecting has never been a problem. It's when Kiro actually tries to call the firecrawl MCP. 

I tried your updated config, butit did not seem to make any difference. 

I will report back if something changes or if I figure it out. Thanks for your efforts on this. 

edit: I should clarify that I tried this in 0.5.0 after restart and everything. The server starts fine, shows the checkmark, and kiro DOES try to call it, but it fails with that error message each time. Other MCPs work fine. The same firecrawl config works fine in all my other apps.

**Comment by Zyuzyawan** [comment]
Доброго, столкнулся с той же проблемой. 
no schema with key or ref "https://json-schema.org/draft/2020-12/schema"
В VScode есть решение данной проблемы через https://github.com/prosser/json-schema-validation-extension ( решение - https://github.com/firecrawl/firecrawl-mcp-server/issues/118 ).
Однако, в Kiro та работать не собирается.

Hello, I've run into the same problem:
no schema with key or ref "https://json-schema.org/draft/2020-12/schema"
In VSCode, there is a solution to this issue using https://github.com/prosser/json-schema-validation-extension (the fix is detailed here: https://github.com/firecrawl/firecrawl-mcp-server/issues/118).
However, that doesn't seem to work in Kiro.

**Comment by lutfi-haslab** [comment]
the error still persist:
2025-11-14 13:32:27.518 [info] [firecrawl] Connected to server with transport type: StreamableHTTP
2025-11-14 13:32:28.769 [info] [firecrawl] Successfully connected and synced tools and resources for MCP server
2025-11-14 13:32:39.668 [error] [firecrawl] Validation failed calling firecrawl_scrape with args {"url":"https://komunitasku.web.id/","formats":["markdown"]}: no schema with key or ref "https://json-schema.org/draft/2020-12/schema"
2025-11-14 13:32:44.764 [error] [firecrawl] Validation failed calling firecrawl_scrape with args {"url":"https://komunitasku.web.id/","formats":["markdown","html"],"onlyMainContent":true}: no schema with key or ref "https://json-schema.org/draft/2020-12/schema"

**Comment by AnilMaktala** [comment]
Thanks for raising this.

Closing this as stale -- it was filed against an older Kiro version and hasn't had activity in several months. If you're still seeing this on the current version, please open a new issue with your Kiro version, OS, and reproduction steps. To update, download from [kiro.dev](https://kiro.dev/).
