### ISSUE TITLE
Remember the Start URL when using "Sign in with your organization identity"

### ISSUE THREAD

**Issue by mt-nym** [kirodotdev/Kiro#3971]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/kirodotdev/Kiro/issues?q=is%3Aissue+)

### Operating System

Mac OS 15.7.2

### Kiro Version

0.6.0

### Bug Description

When using the "Sign in with your organization identity" option with Kiro, the previous Start URL used is not kept in the box requiring it to be entered again. 

### Steps to Reproduce

1. Open Kiro. Select  "Sign in with your organization identity"
2. Enter a valid Start URL and region
3. Complete the sign-in process
4. Wait for your AWS session to expire where Kiro prompts you to login again OR restart Kiro
5. Choose  "Sign in with your organization identity" again
6. The text box for Start URL is empty and does not remember the previous value used

### Expected Behavior

6. The text box for Start URL is populated with the last value provided

### Additional Context

Although this is technically not a bug, it does end up being very painful over time. Most developers don't remember the start URL and are switching to some set of notes to copy/paste it and they have to do it about 2 times per day and every morning. Seems like a small amount of effort to improve the happiness of so many developers. Thanks!

**Comment by es-hunters** [comment]
https://github.com/kirodotdev/Kiro/issues/2296 is related. I have now memorized my start url but is very painful to constantly input.

**Comment by es-hunters** [comment]
https://github.com/kirodotdev/Kiro/issues/3789 is related.

**Comment by es-hunters** [comment]
Also FWIW, the region is also not remembered on the sign in form

**Comment by Survival1sm** [comment]
please fix this!! also, token expiration at 9 hours would be amazing.

**Comment by shiftcontrol-dan** [comment]
+1!!!

**Comment by stefanorg** [comment]
+1

**Comment by preetmyob** [comment]
Adding +1 this is a real pain other wise

**Comment by AnilMaktala** [comment]
Hey @mt-nym, This issue has been addressed in Kiro v0.8.0. The release includes:

**Improvement:** "Enterprise auth - Smoother sign-in with cached enterprise auth startURL"

The Start URL is now cached, so you won't need to re-enter it each time you sign in with your organization identity.

Please update to the latest version and let us know if you're still experiencing this issue. Thanks for reporting!

**Comment by allandsouza** [comment]
Is it possible to apply this fix to kiro-cli?

**Comment by doctau** [comment]
This was working for me, but as of a few days to a week ago, it is no longer remembering the startURL for me, and I need to re-enterit every time after it loads https://app.kiro.dev/signin and select Your Organisation -> IAM identity Centre

**Comment by jmnsilva** [comment]
This is still happening to me on kiro version: 0.12.333 with edge....
