### ISSUE TITLE
pty host loses connection

### ISSUE THREAD

**Issue by smakinson** [kirodotdev/Kiro#4501]
### Before opening, please confirm:

- [x] I have [searched for duplicate or closed issues](https://github.com/kirodotdev/Kiro/issues?q=is%3Aissue+)

### Operating System

darwin

### Kiro Version

0.7.45

### Bug Description

Fairly frequently I see the `Pty Host` button appear in the bottom bar and the script that agent is running does not complete. I need to kill the terminal to proceed (I don't see any other option) It may be related to the length of the script the agent decided to run. This is not when it runs a script from a file, but inline, things that start like: 
```
python -c "
import sys....
```

Similar to this issue: https://github.com/kirodotdev/Kiro/issues/3701 but maybe a little more detail here incase it helps.

### Steps to Reproduce

Work through some Tasks in a conversation and run the scripts presented by the agent. Eventually you will run into this issue.

### Expected Behavior

Connection should not be lost.
If it is lost and I click the `Pty Host` button to restart the terminal ( *  Restarting the terminal because the connection to the shell process was lost... ) and it restarts, it should rerun the script from the agent successfully so the conversation can proceed.

### Conversation ID

f269f694-5637-4835-ac5f-7234cbd1b0a8
b8d9968d-accd-46d3-970c-facbe690b5b2
2e2bd46b-04f8-4d69-a62a-70324bcd751a

### Additional Context

- <img width="333" height="89" alt="Image" src="https://github.com/user-attachments/assets/fc39521e-c821-4bfe-a411-30879193567d" />
- <img width="256" height="156" alt="Image" src="https://github.com/user-attachments/assets/07b03896-477c-49e7-b806-f9b0a87f0772" />
- <img width="381" height="433" alt="Image" src="https://github.com/user-attachments/assets/b5a92494-6bd1-4141-b1ff-a807e52f3d06" />

**Comment by ymotongpoo** [comment]
I have the same issue these days. 

<img width="148" height="40" alt="Image" src="https://github.com/user-attachments/assets/723f5eea-1d2c-4dfd-9586-d4ec26acfe9b" />

**Comment by phdws** [comment]
Same problem here, usually happens on: uv run python -c "..."

**Comment by cmworkato** [comment]
Also happens when a file edit fails and Kiro tries to recreate files with:

echo
<<EOF
foo
bar
EOF

**Comment by mt-nym** [comment]
@AnilMaktala I don't know for sure, but this seems to be an issue in the underlying VS Code reported in this bug:
https://github.com/microsoft/vscode/issues/246204

And a FIX! in this commit:
https://github.com/microsoft/vscode/pull/283065

I can't tell exactly what VS Code release this is in or will be in, but tracking this fix and getting it into Kiro will probably address this issue. Other potentially related Kiro issues:
 https://github.com/kirodotdev/Kiro/issues/4754
https://github.com/kirodotdev/Kiro/issues/3701
https://github.com/kirodotdev/Kiro/issues/3230
https://github.com/kirodotdev/Kiro/issues/3208

**Comment by deltaguita** [comment]
same issue

**Comment by AnilMaktala** [comment]
Hi all, Thanks for reporting this and for the detailed information — we appreciate the Conversation IDs and screenshots.

We're actively working on this issue and tracking a fix. We'll update this thread once the fix is available.

Thanks for your patience!

**Comment by KaimingWan** [comment]
same question, and it's annoying

**Comment by AnilMaktala** [comment]
Hello All,  We've fixed the terminal crash caused by long, multi-line inline shell commands (e.g., python -c "...") that was causing the PTY host to lose connection. This fix is available in v0.9.0.
Please upgrade to the latest version and let us know if the issue persists. We'll close this once confirmed.

Thanks for your patience!

**Comment by mt-nym** [comment]
I upgraded to v0.9.0 and have not seen the Pty Host disconnect issue since the upgrade. It appears to be fixed for how I use Kiro. Thank you for getting this resolved.

**Comment by mpasang** [comment]
I'm using version 0.9.2, and I'm still encountering the  unresponsive pty process:

<img width="513" height="233" alt="Image" src="https://github.com/user-attachments/assets/41d8c9e1-06b0-450e-b5f8-6507b8f46bb8" />

<img width="1753" height="406" alt="Image" src="https://github.com/user-attachments/assets/a8a97c44-feb7-4693-94c6-6117c85657ef" />

**Comment by patrickmetz** [comment]
It has not been fixed for me. I have a fresh install of Kiro 0.10.32

And I still get "*  Restarting the terminal because the connection to the shell process was lost... " until the "Pty Host" button appears.

**Steps to reproduce A)**
- Start Kiro
- Open Terminal
- > immediately loses connection to the shell process

**Steps to reproduce B)**
- Let any agent do any shell command
- > agent skips terminal command 

**OS**
Ubuntu 24.04.4 LTS

**Kiro**
Version: 0.10.32
VSCode Version: 1.107.1
Commit: 0f0b5b6c39b3c793d552412c0c215714dff2fcef
Date: 2026-02-23T23:21:55.661Z
Electron: 39.2.3
Chromium: 142.0.7444.175
Node.js: 22.21.1
V8: 14.2.231.21-electron.0
OS: Linux x64 6.17.0-14-generic

**Main Log**
2026-03-06 13:45:16.248 [info] update#setState idle
2026-03-06 13:45:23.072 [error] ptyHost terminated unexpectedly with code 133
2026-03-06 13:45:23.075 [warning] [UtilityProcess type: ptyHost, pid: 14031]: unable to kill the process
2026-03-06 13:45:24.869 [error] ptyHost terminated unexpectedly with code 133
2026-03-06 13:45:24.870 [warning] [UtilityProcess type: ptyHost, pid: 14108]: unable to kill the process
2026-03-06 13:45:26.623 [error] ptyHost terminated unexpectedly with code 133
2026-03-06 13:45:26.624 [warning] [UtilityProcess type: ptyHost, pid: 14157]: unable to kill the process
2026-03-06 13:45:27.982 [error] ptyHost terminated unexpectedly with code 133
2026-03-06 13:45:27.986 [warning] [UtilityProcess type: ptyHost, pid: 14206]: unable to kill the process
2026-03-06 13:45:29.475 [error] ptyHost terminated unexpectedly with code 133
2026-03-06 13:45:29.476 [warning] [UtilityProcess type: ptyHost, pid: 14246]: unable to kill the process
2026-03-06 13:45:30.698 [error] ptyHost terminated unexpectedly with code 133
2026-03-06 13:45:30.698 [warning] [UtilityProcess type: ptyHost, pid: 14280]: unable to kill the process
2026-03-06 13:45:31.961 [error] ptyHost terminated unexpectedly with code 133, giving up
2026-03-06 13:45:31.962 [error] [UtilityProcess type: ptyHost, pid: 14313]: crashed with code 133 and reason 'crashed'
2026-03-06 13:45:46.180 [info] update#setState checking for updates
2026-03-06 13:45:46.775 [info] update#setState available for download
2026-03-06 13:45:50.709 [warning] No ptyHost heartbeat after 6 seconds
2026-03-06 13:45:55.712 [error] No ptyHost heartbeat after 12 seconds
2026-03-06 14:20:27.275 [error] ptyHost terminated unexpectedly with code 133, giving up
2026-03-06 14:20:27.278 [error] [UtilityProcess type: ptyHost, pid: 14969]: crashed with code 133 and reason 'crashed'
2026-03-06 14:20:45.697 [warning] No ptyHost heartbeat after 6 seconds
2026-03-06 14:20:50.705 [error] No ptyHost heartbeat after 12 seconds

**Terminal Log**
2026-03-06 13:45:23.130 [error] The terminal's pty host process exited, the connection to all terminal processes was lost []
2026-03-06 13:45:24.874 [error] The terminal's pty host process exited, the connection to all terminal processes was lost []
2026-03-06 13:45:26.656 [error] The terminal's pty host process exited, the connection to all terminal processes was lost []
2026-03-06 13:45:28.001 [error] The terminal's pty host process exited, the connection to all terminal processes was lost []
2026-03-06 13:45:29.489 [error] The terminal's pty host process exited, the connection to all terminal processes was lost []
2026-03-06 13:45:30.708 [error] The terminal's pty host process exited, the connection to all terminal processes was lost []
2026-03-06 13:45:31.964 [error] The terminal's pty host process exited, the connection to all terminal processes was lost []
2026-03-06 14:20:25.660 [warning] Restarting pty host for authority "undefined" []
2026-03-06 14:20:27.280 [error] The terminal's pty host process exited, the connection to all terminal processes was lost []

**EDIT**
I upgraded to Kiro version 0.10.78 today. Terminal is still broken.

**Comment by halmaikristof** [comment]
If you're looking for a workaround:
For me building node-pty manually (on target) and replacing pty.node in Kiro files (`resources/app/node_modules/node-pty/build/Release/pty.node`) solves the issue.
https://github.com/microsoft/node-pty

**Comment by amilbourne** [comment]
I am running IDE 1.12.333 and seeing the same issue.  It mostly happens when an agent tries to cat content to a file as this is generally many lines.  When the agent does this, the command succeeds almost immediately in the terminal window, but the agent sits in 'Working...' state indefinitely.  I do not see the 'Pty Host' button that others have talked about.  Sometimes killing the terminal window helps, but it doesn't seem to be a reliable fix.
